# Generated by Django 2.1.7 on 2019-03-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
