# Generated by Django 2.1.7 on 2019-03-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractbase', '0003_auto_20190301_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
    ]
